import { Machine, Ticket } from './types';

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'PLASMA-GEN-001',
    name: 'High-Temp Plasma Reactor 001',
    location: 'Facility Alpha - Sector 4B',
    x: 28,
    y: 35,
    status: 'ERROR',
    temperature: 87.4,
    vibration: 8.2,
    power_kw: 142.5,
    rpm: 12400,
    firmware: 'v2.4.1-edge',
    lastPing: '2s ago',
    ip_address: '10.240.12.101',
  },
  {
    id: 'PLASMA-GEN-002',
    name: 'High-Temp Plasma Reactor 002',
    location: 'Facility Alpha - Sector 4C',
    x: 62,
    y: 42,
    status: 'WARNING',
    temperature: 71.8,
    vibration: 4.1,
    power_kw: 118.0,
    rpm: 11800,
    firmware: 'v2.4.1-edge',
    lastPing: '1s ago',
    ip_address: '10.240.12.102',
  },
  {
    id: 'PLASMA-GEN-003',
    name: 'High-Temp Plasma Reactor 003',
    location: 'Facility Beta - Bay 12',
    x: 78,
    y: 72,
    status: 'HEALTHY',
    temperature: 54.2,
    vibration: 1.8,
    power_kw: 98.4,
    rpm: 10500,
    firmware: 'v2.5.0-edge',
    lastPing: 'Just now',
    ip_address: '10.240.14.055',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    ticket_id: 'TCK-8841',
    machine_id: 'PLASMA-GEN-001',
    priority: 'P1',
    description: 'Thermal runaway threshold breached (>85°C) in primary magnetic containment coil stage 2.',
    ai_runbook: `1. Check cooling fluid pressure on manifold lines 2A/2B.\n2. Execute emergency throttle command or issue C2D STOP if temp exceeds 90°C.\n3. Run diagnostic check: \`aws iot-data publish --topic c2d/plasma-001/diag --payload '{"action":"scan_coolant"}'\`\n4. Inspect inverter thermal logs before restarting node.`,
    status: 'OPEN',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    telemetry_snapshot: {
      temperature: 87.4,
      vibration: 8.2,
      power_kw: 142.5,
      rpm: 12400,
    },
  },
  {
    ticket_id: 'TCK-8839',
    machine_id: 'PLASMA-GEN-002',
    priority: 'P2',
    description: 'Elevated harmonic vibration (4.1 mm/s) detected during high-load power cycle.',
    ai_runbook: `1. Verify rotor balance alignment on axis B.\n2. Push firmware update v2.5.0-edge containing vibration dampening patch.\n3. Re-calibrate sensor array using \`c2d_cmd --node 002 --action calibrate\`.\n4. Monitor telemetry for 15 minutes post-patch.`,
    status: 'OPEN',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    telemetry_snapshot: {
      temperature: 71.8,
      vibration: 4.1,
      power_kw: 118.0,
      rpm: 11800,
    },
  },
  {
    ticket_id: 'TCK-8812',
    machine_id: 'PLASMA-GEN-003',
    priority: 'P4',
    description: 'Routine telemetry diagnostic notice: Scheduled firmware validation check due.',
    ai_runbook: `1. Verify node running build v2.5.0-edge.\n2. Confirm telemetry ping rate under 50ms.\n3. No manual intervention required unless error flag trips.`,
    status: 'RESOLVED',
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    telemetry_snapshot: {
      temperature: 54.2,
      vibration: 1.8,
      power_kw: 98.4,
      rpm: 10500,
    },
  },
];
